import type { SurveyResponseRow } from "./survey-aggregate";

/** 15 fictional responses when the DB is empty or Supabase cannot be reached. */
export const SURVEY_DEMO_ROWS: SurveyResponseRow[] = [
  {
    favorite_artist: "Taylor Swift",
    genre: "Pop",
    college_year: "2nd Year",
    platforms: JSON.stringify(["Spotify", "Apple Music"]),
    other_platform: null,
  },
  {
    favorite_artist: "Kendrick Lamar",
    genre: "Hip-Hop / Rap",
    college_year: "3rd Year",
    platforms: JSON.stringify(["Spotify", "YouTube"]),
    other_platform: null,
  },
  {
    favorite_artist: "The Beatles",
    genre: "Rock / Metal",
    college_year: "4th Year",
    platforms: JSON.stringify(["Apple Music", "Radio"]),
    other_platform: null,
  },
  {
    favorite_artist: "Billie Eilish",
    genre: "Indie / Alternative",
    college_year: "1st Year",
    platforms: JSON.stringify(["Spotify"]),
    other_platform: null,
  },
  {
    favorite_artist: "Bad Bunny",
    genre: "Latin",
    college_year: "2nd Year",
    platforms: JSON.stringify(["Spotify", "YouTube"]),
    other_platform: null,
  },
  {
    favorite_artist: "Fred again..",
    genre: "Electronic / EDM",
    college_year: "5th Year or More",
    platforms: JSON.stringify(["SoundCloud", "Spotify"]),
    other_platform: null,
  },
  {
    favorite_artist: "Jon Batiste",
    genre: "Jazz / Blues",
    college_year: "3rd Year",
    platforms: JSON.stringify(["Apple Music", "Radio"]),
    other_platform: null,
  },
  {
    favorite_artist: "BLACKPINK",
    genre: "K-Pop",
    college_year: "1st Year",
    platforms: JSON.stringify(["YouTube", "Spotify"]),
    other_platform: null,
  },
  {
    favorite_artist: "Luke Combs",
    genre: "Country",
    college_year: "4th Year",
    platforms: JSON.stringify(["Apple Music", "Radio"]),
    other_platform: null,
  },
  {
    favorite_artist: "SZA",
    genre: "R&B / Soul",
    college_year: "2nd Year",
    platforms: JSON.stringify(["Spotify"]),
    other_platform: null,
  },
  {
    favorite_artist: "Hans Zimmer",
    genre: "Classical",
    college_year: "5th Year or More",
    platforms: JSON.stringify(["Apple Music", "YouTube"]),
    other_platform: null,
  },
  {
    favorite_artist: "Phoebe Bridgers",
    genre: "Indie / Alternative",
    college_year: "3rd Year",
    platforms: JSON.stringify(["Spotify", "Other"]),
    other_platform: "Bandcamp",
  },
  {
    favorite_artist: "Drake",
    genre: "Hip-Hop / Rap",
    college_year: "2nd Year",
    platforms: JSON.stringify(["Spotify", "Apple Music", "YouTube"]),
    other_platform: null,
  },
  {
    favorite_artist: "Arctic Monkeys",
    genre: "Rock / Metal",
    college_year: "1st Year",
    platforms: JSON.stringify(["Spotify", "SoundCloud"]),
    other_platform: null,
  },
  {
    favorite_artist: "Rosalía",
    genre: "Latin",
    college_year: "4th Year",
    platforms: JSON.stringify(["YouTube", "Apple Music"]),
    other_platform: null,
  },
];
